### ISSUE TITLE
[Android] Opening note redirects to browser

### ISSUE THREAD

**Issue by bipox** [TheodoreChu/flashcard-editor#7]
Hi, 

Using the SN app (latest github version) on Android 10. 

The flashcard editor redirects to the demo page in a browser. 

It still works with webapp and desktop.

**Comment by TheodoreChu** [comment]
Hi @bipox,

Thanks for pointing this out. It should be fixed now. If not, please re-install the editor.

The issue was that, in the JSON file used to import the editor, I changed the `hosted_url` from `https://demo.flashcardeditor.com/dist/index.html` to `https://demo.flashcardeditor.com/` because I want to eventually migrate the latter. I set up the latter to redirect to the former while I perform the migration, but the mobile app doesn't handle redirects properly, so it keeps redirecting you in a browser. I reverted the change for now so that you can use the former directly. When I eventually perform the URL migration, however, you will need to re-install the editor again. This won't happen for a few months, however, since I don't have the time/resources to work on the editor for now.

**Comment by bipox** [comment]
Thanks @TheodoreChu !

I'm very glad you've fixed it, as I'm quite fond of having flashcards in SN instead of using Anki or another dedicated app.

The issue is still there using thttps://raw.githubusercontent.com/TheodoreChu/flashcard-editor/develop/demo.ext.json 
It works with https://notes.theochu.com/p/FV2A4HJFRN
(or maybe it was just a coincidence and something else went wrong)

Cheers

**Comment by TheodoreChu** [comment]
Hi @bipox, it's nice to hear that you are quite fond of having flashcards in SN. I hope to work on this editor more in the future.

I fixed the `url` in the JSON hosted on Listed (notes.theochu.com) but forgot to fix it in the GitHub repository. It should be fixed here: https://github.com/TheodoreChu/flashcard-editor/commit/0fd06c41e5b7207924e0dc621b2b69289d5edbc7.

Please let me know if you notice any more issues and I'll try to fix them in the future. 🙂
